version: "3.7"
services:
  manager:
    image: opendigitaltwin/manager
    environment:
      - MQTT_CLUSTER_IP=emqx.dtwins
      - MQTT_CLUSTER_PORT='18083'
      - MQTT_SUBSCRIBED_TOPIC='sometopic/somelevel'
      - MQTT_QOS=0
      - MQTT_SECRETS='secret'
    restart: always