[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=53.0.0",
    "build",
    "wheel",
    'cffi',
]

# pytest configuration
[tool.pytest.ini_options]
addopts = "--capture=no --verbose"
